services:
  tube-sorter:
    build: .
    image: tube-sorter:latest
    container_name: tube-sorter
    restart: unless-stopped
    environment:
      - CHECK_CHANNELS_EVERY_HOURS=24
      - NUMBER_OF_VIDEOS_TO_PROCESS=5
      - TZ=Europe/Madrid
    volumes:
      - ./secrets:/app/secrets
      - ./config:/app/config